### PR TITLE
Add dependencies in the zip

### PR DESCRIPTION
**Pull request by samuel-soubeyran**
Add an option to specify a list of folders containing dependencies to add to the zip

### CODE REVIEW

**Comment by samuel-soubeyran** [comment]
I didn't see the pull request #35 wich seems to have a better solution for this problem....

**Comment by samuel-soubeyran** [comment]
After looking to the PR #35, it doesn't solve the same issue, which is avoiding to mix the source code with the dependencies. 

From the exemple in PR #35 we have to install the dependencies in the same folder before deploying, wich I find messy at best, and problematic for certain use case. For exemple to use psycopg2 we need to override the folder to use the version compiled on the same AMI as the one running the lambda. This is very easy when you can specify folder of dependencies.

As Kalpit said in the PR #35, it begins to be difficult to know against which branch we should do the PR. I can also do a PR against python-refactor if needed.


Thanks,

**Comment by garnaat** [comment]
The python-refactor branch is the right one to base changes on.  I apologize that it has been hanging out for so long and I will try to get it merged asap.  We use kappa (on the python-refactor branch) every day here but I just haven't been able to find the time to complete the docs and examples needed to complete the merge.

**Comment by garnaat** [comment]
So, if I understand correctly, it would be helpful to you to have this merged into the develop branch, correct?  Is that the branch you are currently using?  Do you still need this merged into python-refactor or was that just for my benefit?

**Comment by samuel-soubeyran** [comment]
From now on I'll be using python-refactor.
So I would rather have python-refactor with my other PR merged and this one doesn't really need to be merged.

Thanks

**Comment by garnaat** [comment]
ok, thanks.

**Pull request closed without merging**
