### PR TITLE
add dependencies and check for existing key in zip before writing new…

### PR DESCRIPTION
**Pull request by samuel-soubeyran**
… file.

This feature add a  "dependencies" parameter to the "lambda" configuration. This parameters consist of a list of resources to add to the zip file. As an exemple, here is how I use it : 
```
lambda:
  name: testKappaDeployer
  description: Testing kappa
  dependencies:
    - transformer.py
    - table_definitions.py
    - core.py
    - formatter.py
    - ami_built_modules
    - venv/lib/python2.7/site-packages
  handler: loader.lambda_handler
  runtime: python2.7
  memory_size: 128
  timeout: 3
  test_data: test/simpleS3test.json
```

### CODE REVIEW

**Comment by garnaat** [comment]
I'm curious about your use case.  It's something I haven't run into, I guess.  I just create a directory, put my code in there with a requirements.txt file and then ``pip install -r requirements.txt -t .`` and I'm good to go.  I'm fine merging this in, just kind of wanted to understand how you are using it.

**Comment by samuel-soubeyran** [comment]
Sure,
My use case is the following:
I work on the tooling in a team with non expert python and datascience expert. The idea is to have a clean code base with a minimum of management to do.

What I want to achieve is to tell the team:
1 -  use a classical virtualenv
2 - write your code and requirements.
3 - pip install - r requirements
4 - run kappa deploy / run
5 - git commit & push
That's it

As you said, actually it feels like:
1 - write your code
2 - pip install -r requirements.txt -t .
3 - run kappa deploy / run
4 - clean the directory <-- ??
5 - git commit & push

The step 4 is what bother me, it feels like there is a lot of manual things not easily automated in this 4th step that I want to avoid. See also how in the first exemple 3 and 4 (and even 5) could be done in a small script if need be, allowing to streamline even more. Not a big difference, but it adds a lot flexibility. But maybe I misunderstood your deployment process and there is an easy way to achieve something similar to the first process with what already exist (that is: without manual file manipulation in the deploy process).

**Comment by garnaat** [comment]
One thing I have been thinking about and experimenting with a bit is using a virtualenv for each Lambda function.  Then the process would look pretty much like your first example.

What would have to happen on the kappa side is that rather than just zipping up the whole ``_src`` directory kappa would have to follow the procedure described here.  Also, we would need to filter some things out of the zip file since they would already be installed in the Lambda container (e.g. boto3) but kappa is already doing that.

The only reason I have hesitated is that I wondered if having a virtualenv for every Lambda function might be a bit too much overhead.

Would that approach work for you?

**Comment by samuel-soubeyran** [comment]
I envision one virtualenv per lambda function. It provides a nice isolation and self containing artifact.
I think the overhead (source venv/bin/activate - deactivate) is well worth the easier dependencies management and isolation (different version of libs for different lambda function, ...etc).

I don't really get what you mean by "rather than just zipping up the whole _src directory kappa would have to follow the procedure described here". If you mean, that kappa would run pip install and then clean the directory, I feel it is adding to much logic (furthermore specific to python) in the tooling. I would rather have the user declare what he wants/ don't want in the zip than trying to guess what he wants.

As an exemple, we currently have this use case where we need to override a lib from the pip install (psycopg2) because the one we get from pip install (on mac) is not compatible with the AMI used by amazon lambda. This is easily done with my current implementation (just declare the good one before the virtualenv one in the dependencies list), it would be much harder if kappa tried to guess what I really wants based on the requirements file.

Hope this clarify a bit.

P.S. I added the dependencies property because I wanted to be compatible with the existing, In my mind, the best would be instead of having a source property taking only a parameter, having a source parameter taking a list of parameters : the list folder content / files to put in the zip...

**Comment by garnaat** [comment]
Probably adding the actual link to *here* above would help a bit.  Sorry.

**Comment by garnaat** [comment]
So, my thought was you:

- set up a virtualenv
- install your dependencies via ``pip install -r requirements.txt``
- deploy finds the right things to upload by looking in the ``site-packages`` of the virtualenv
- kappa removes things that are already in the container

It sounds like that is a good flow for you but not enough.  You still want the ability to add extra dependencies.  I would like to support that but would also like things to "just work" for most people who have simpler requirements and don't want to list every dependency.

So, if we can come up with a way to do that, that would be awesome.  And I don't mind changing the ``kappa.yml`` file because there are already many breaking changes in this branch.

**Comment by samuel-soubeyran** [comment]
Well this would be better for sure,
But this wouldn't solve everything,

For one I still want to override some libs that are incompatible from mac to lambda AMI. The second reason is that it is very python focused and I feel that your tool is handling nodejs, python and could even go to java. Being so tightly coupled to python might not be what you want. Finally, it seems that it would need a lot of dev time and I would rather have a workable, less than perfect solution in the master branch   with all the python-refactor branch than to add some features request on the python-refactor. We could then improve on it on smaller PR.

**Comment by samuel-soubeyran** [comment]
BTW, you could have a look to this for inspiration: 
https://github.com/rackerlabs/lambda-uploader

They have an awesome virtualenv handling, but lack a lot of the tooling of kappa. Which is why I use kappa. For me the value of kappa is not on the handling of virtualenv, but on the ability to test/deploy/version/etc... It just misses a workable solution to add dependencies :)

**Comment by garnaat** [comment]
I have merged this in, as is.  It's possible that this will change over time but now that I understand your use case I think I can at least retain the desired functionality.

Thanks.

**Comment by samuel-soubeyran** [comment]
Thanks,
I really appreciate it.

Samuel

2016-02-12 12:19 GMT-08:00 Mitch Garnaat <notifications@github.com>:

**Pull request merged**
