### PR TITLE
Adding optional logs rentention policy, Fixing issue that only allowed one sns event source to be added

### PR DESCRIPTION
**Pull request by olabhrad**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you squash your commits into one?

**Comment by olabhrad** [comment]
Squash was done.

**Comment by josegonzalez** [comment]
Oh, also needs documentation. Sorry!

**Comment by olabhrad** [comment]
What documentation would you like me to update? I've added an example to docs/config_file_example.rst so the logs retention policy is as well documented as say runtime, memory_size or timeout.

**Comment by olabhrad** [comment]
Any update with this?

**Comment by josegonzalez** [comment]
Just usage documentation in the readme is fine.

**Comment by olabhrad** [comment]
Updated README

**Comment by olabhrad** [comment]
Can this be merged?

**Pull request merged**
