### PR TITLE
Adding support for environment variables

### PR DESCRIPTION
**Pull request by BrunoCarrier**
Hi, this pull request allows for environment variables to be used
At the environment level, if the environment_variables key is present with a dictionary, it will add it to the update_configuration and create methods.  Otherwise, it will send blank data which effectively removes any existing environment variables

The _check_config_md5 method will also consider changes in the yml file, and will update lambda function configuration if any change is detected

I added an example to the kamma-simple project

### CODE REVIEW

**Comment by BrunoCarrier** [comment]
I'm not sure why 8 other commits were bundled in here, since I forked from the main repository lately.  Any idea?

**Comment by josegonzalez** [comment]
You probably branched from master and are pull requesting to develop.

**Comment by BrunoCarrier** [comment]
Nah they're both from develop - "BrunoCarrier  wants to merge 9 commits into garnaat:develop from BrunoCarrier:develop"

**Comment by BrunoCarrier** [comment]
@josegonzalez  @garnaat, is there anything needing to be done so that this is included in the next release?  Is there an ETA for the next release?

**Comment by josegonzalez** [comment]
ETA is whenever someone gets to it. I have a day job that pays bills, open source does not. I'll look at this when I get a chance.

Note: you'll need to figure out how to remove all those extra commits from the pull request.

**Comment by BrunoCarrier** [comment]
@josegonzalez That sounds good and is absolutely understandable :-)  I appreciate the reply

I've fixed the extra commits issue through this other pull request:https://github.com/garnaat/kappa/pull/98

Consequently, I will close this current PR

**Pull request closed without merging**
